/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    Calendarmodal: typeof import('./src/components/Modals/Calendar/Calendarmodal.vue')['default']
    Course_modal: typeof import('./src/components/Modals/Course/Course_modal.vue')['default']
    Course_model: typeof import('./src/components/Modals/Course/Course_model.vue')['default']
    Edit_course: typeof import('./src/components/Modals/Course/Edit_course.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowDetail: typeof import('./src/components/Modals/Showdetail/showDetail.vue')['default']
    User: typeof import('./src/components/Modals/Edit_Reservation/user.vue')['default']
  }
}
